//! Kill switch — block all non-tunnel traffic via nftables while a tunnel is up.
//!
//! # Design
//!
//! The kill switch uses a **uniquely-named nftables table** (`inet wg_gui_killswitch`) so it
//! never collides with or alters any other firewall on the system.  The output chain has a
//! `policy drop` that blocks everything *except* the explicitly allowed paths listed below.
//!
//! ## Allow-list ordering (lockout-prevention rules MUST come first)
//!
//! 1. `oifname "lo"` — loopback always passes (local IPC, DNS-on-localhost, etc.)
//! 2. `oifname <wg-iface>` — outbound tunnel traffic itself is accepted
//! 3. `ip daddr <endpoint_ip> udp dport <endpoint_port>` — the WireGuard endpoint UDP so the
//!    daemon can reconnect even when the kill switch is armed; this is the punch-through hole
//!    that makes the dead-man-timer lease work correctly
//! 4. LAN/RFC1918 CIDRs (user-configurable) — keeps local network access live
//! 5. `ct state established,related` — return traffic for already-established sessions
//! 6. Optional per-app netns UDP punch-through — the netns-side endpoint UDP so per-app
//!    namespaces can still reach the WireGuard server
//!
//! Everything else hits the output chain's `policy drop`.
//!
//! ## Fail-safe: dead-man timer (lease)
//!
//! When the helper arms the kill switch it also schedules a `systemd-run` one-shot unit:
//!
//! ```text
//! systemd-run --on-active=<lease_secs>s \
//!             --unit=wg-gui-killswitch-reaper \
//!             --description="WireGuard GUI kill-switch lease reaper" \
//!             nft delete table inet wg_gui_killswitch
//! ```
//!
//! If the GUI process is killed (SIGKILL, crash, power loss) without disarming, the kernel
//! timer fires after `lease_secs` seconds and removes the blocking table automatically.  The
//! GUI renews the lease before it expires by issuing a fresh [`PrivCmd::KillSwitchArm`] (which
//! re-creates the table + timer atomically).
//!
//! ## Boot reconciliation
//!
//! On startup the GUI (or the helper, called once) checks for an orphaned `wg_gui_killswitch`
//! table with no live WireGuard interface present and removes it by calling
//! [`PrivCmd::KillSwitchDisarm`].
//!
//! ## Privilege boundary
//!
//! This module is **pure GUI-side**.  It builds [`PrivCmd`] values and constructs the nft
//! script text; it never applies any ruleset.  The actual `nft -f <file>` or
//! `nft delete table …` invocations happen inside the root helper binary.

use crate::error::AppResult;
use crate::net::privilege::{encode, run_privileged, PrivCmd};

// ─────────────────────────────────────────────────────────────────────────────
// Ruleset generation (pure, no side effects, golden-testable)
// ─────────────────────────────────────────────────────────────────────────────

/// The nftables table name used exclusively by this application.
///
/// Uniquely named so it never collides with any other firewall policy on the host.
pub const NFT_TABLE: &str = "inet wg_gui_killswitch";

/// Build the complete `nft -f` script that installs the kill-switch ruleset.
///
/// The returned string is a self-contained nftables script that:
/// - Flushes any pre-existing `wg_gui_killswitch` table (idempotent re-arm)
/// - Creates `table inet wg_gui_killswitch`
/// - Adds an `output` chain with `policy drop`
/// - Prepends the **lockout-prevention allow-list** in the correct priority order before the
///   implicit policy drop
///
/// # Parameters
///
/// - `iface` — the WireGuard interface name (e.g. `wg-gui-home`)
/// - `endpoint_ip` — the WireGuard server's public IP address
/// - `endpoint_port` — the WireGuard server's UDP port
/// - `lan_cidrs` — slice of LAN/RFC1918 CIDRs to keep reachable (may be empty)
/// - `netns_endpoint_udp` — optional `(ip, port)` for a per-app netns punch-through
///
/// # Guarantee
///
/// This function is **pure** and never executes any command.  Pass the output to a temp file
/// and invoke `nft -c -f <file>` (syntax check only) or let the helper run `nft -f <file>`.
pub fn build_ruleset(
    iface: &str,
    endpoint_ip: &str,
    endpoint_port: u16,
    lan_cidrs: &[&str],
    netns_endpoint_udp: Option<(&str, u16)>,
) -> String {
    let mut lines: Vec<String> = Vec::new();

    // Flush then recreate — makes re-arming idempotent without a separate disarm step.
    lines.push("# wg_gui_killswitch — generated by wireguard-gui-rust".to_string());
    lines.push("# DO NOT EDIT MANUALLY — managed by wireguard-gui-helper".to_string());
    lines.push(String::new());
    // Silently ignore the flush if the table does not exist yet (first arm).
    lines.push("add table inet wg_gui_killswitch".to_string());
    lines.push("delete table inet wg_gui_killswitch".to_string());
    lines.push(String::new());
    lines.push("table inet wg_gui_killswitch {".to_string());
    lines.push("    chain output {".to_string());
    lines.push("        type filter hook output priority 0;".to_string());
    lines.push("        policy drop;".to_string());
    lines.push(String::new());
    lines.push("        # ── lockout-prevention allow-list ──────────────────────────────".to_string());
    lines.push("        # Rule 1: loopback — always allow (IPC, local DNS, etc.)".to_string());
    lines.push("        oifname \"lo\" accept;".to_string());
    lines.push(String::new());
    lines.push("        # Rule 2: outbound tunnel traffic through the WireGuard interface".to_string());
    lines.push(format!("        oifname \"{iface}\" accept;"));
    lines.push(String::new());
    lines.push("        # Rule 3: WireGuard endpoint UDP — punch-through for (re)connect".to_string());
    lines.push(format!(
        "        ip daddr {endpoint_ip} udp dport {endpoint_port} accept;"
    ));
    lines.push(String::new());

    // Rule 4: LAN/RFC1918 CIDRs.
    if !lan_cidrs.is_empty() {
        lines.push("        # Rule 4: LAN/RFC1918 CIDRs".to_string());
        for cidr in lan_cidrs {
            lines.push(format!("        ip daddr {cidr} accept;"));
        }
        lines.push(String::new());
    } else {
        lines.push("        # Rule 4: LAN/RFC1918 CIDRs (none configured)".to_string());
        lines.push(String::new());
    }

    // Rule 5: established / related return traffic.
    lines.push("        # Rule 5: established / related return traffic".to_string());
    lines.push("        ct state established,related accept;".to_string());
    lines.push(String::new());

    // Rule 6: optional per-app netns UDP punch-through.
    if let Some((ns_ip, ns_port)) = netns_endpoint_udp {
        lines.push("        # Rule 6: per-app netns endpoint UDP punch-through".to_string());
        lines.push(format!(
            "        ip daddr {ns_ip} udp dport {ns_port} accept;"
        ));
        lines.push(String::new());
    } else {
        lines.push("        # Rule 6: per-app netns UDP punch-through (not configured)".to_string());
        lines.push(String::new());
    }

    lines.push("        # Everything else is dropped by the chain policy.".to_string());
    lines.push("    }".to_string());
    lines.push("}".to_string());
    lines.push(String::new()); // trailing newline

    lines.join("\n")
}

// ─────────────────────────────────────────────────────────────────────────────
// Client-side helpers — build and dispatch PrivCmd values
// ─────────────────────────────────────────────────────────────────────────────

/// Client-side kill-switch controller.
///
/// All methods are **pure builders or async dispatchers**.  The actual nft execution happens
/// only inside the root helper binary (via `pkexec`); this struct never runs privileged code.
pub struct KillSwitch;

impl KillSwitch {
    /// Arm the kill-switch for `iface`.
    ///
    /// Builds a [`PrivCmd::KillSwitchArm`] and dispatches it through the privileged helper.
    /// The helper will:
    /// 1. Verify `iface` is present (`ip link show <iface>`) — refuses if absent.
    /// 2. Write the ruleset to a temp file and run `nft -f <file>`.
    /// 3. Schedule the dead-man timer:
    ///    ```text
    ///    systemd-run --on-active=<lease_secs>s \
    ///                --unit=wg-gui-killswitch-reaper \
    ///                --description="WireGuard GUI kill-switch lease reaper" \
    ///                nft delete table inet wg_gui_killswitch
    ///    ```
    ///
    /// # Dead-man timer
    ///
    /// The `lease_secs` parameter bounds the maximum time the kill-switch stays active without
    /// a renewal.  The GUI must call `arm` again before `lease_secs` elapse to reset the timer;
    /// if the GUI is killed (SIGKILL, crash), the reaper unit fires automatically.
    pub async fn arm(
        &self,
        iface: &str,
        endpoint_ip: &str,
        endpoint_port: u16,
        lan_cidrs: Vec<String>,
        lease_secs: u64,
        netns_endpoint_udp: Option<(String, u16)>,
    ) -> AppResult<()> {
        let cmd = PrivCmd::KillSwitchArm {
            iface: iface.to_owned(),
            endpoint_ip: endpoint_ip.to_owned(),
            endpoint_port,
            lan_cidrs,
            lease_secs,
            netns_endpoint_udp,
        };
        run_privileged(&cmd).await
    }

    /// Disarm the kill-switch by removing the `wg_gui_killswitch` table.
    ///
    /// Builds a [`PrivCmd::KillSwitchDisarm`] and dispatches it.  The helper runs:
    /// `nft delete table inet wg_gui_killswitch`.
    ///
    /// Idempotent: if the table does not exist the helper should treat the nft error as a no-op.
    pub async fn disarm(&self) -> AppResult<()> {
        run_privileged(&PrivCmd::KillSwitchDisarm).await
    }

    /// Build the [`PrivCmd::KillSwitchArm`] payload **without dispatching it**.
    ///
    /// Use this for golden-string tests, dry-run previews, or anywhere the JSON wire shape
    /// must be inspected without executing anything.
    pub fn arm_cmd(
        iface: &str,
        endpoint_ip: &str,
        endpoint_port: u16,
        lan_cidrs: Vec<String>,
        lease_secs: u64,
        netns_endpoint_udp: Option<(String, u16)>,
    ) -> AppResult<String> {
        let cmd = PrivCmd::KillSwitchArm {
            iface: iface.to_owned(),
            endpoint_ip: endpoint_ip.to_owned(),
            endpoint_port,
            lan_cidrs,
            lease_secs,
            netns_endpoint_udp,
        };
        encode(&cmd)
    }

    /// Build the [`PrivCmd::KillSwitchDisarm`] payload without dispatching it.
    pub fn disarm_cmd() -> AppResult<String> {
        encode(&PrivCmd::KillSwitchDisarm)
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use std::process::Command;

    use super::*;

    // ── Helper ────────────────────────────────────────────────────────────────

    /// Write `content` to a uniquely-named temp file and return the path.
    /// The caller is responsible for deletion (handled by `tempfile::NamedTempFile`).
    fn write_temp_ruleset(content: &str) -> tempfile::NamedTempFile {
        use std::io::Write as _;
        let mut f = tempfile::NamedTempFile::new().expect("create temp file");
        f.write_all(content.as_bytes()).expect("write ruleset");
        f
    }

    // ── build_ruleset: golden-string ordering ─────────────────────────────────

    /// Rule 1 (lo) must precede Rule 2 (wgif), Rule 2 must precede Rule 3 (endpoint UDP),
    /// Rule 3 must precede Rule 5 (established), and the drop policy header must be present.
    #[test]
    fn allow_list_ordering_lo_then_wgif_then_endpoint_then_lan_then_established() {
        let ruleset = build_ruleset(
            "wg-gui0",
            "203.0.113.7",
            51820,
            &["192.168.0.0/16", "10.0.0.0/8"],
            None,
        );

        // The policy must be there.
        assert!(
            ruleset.contains("policy drop"),
            "missing 'policy drop' in:\n{ruleset}"
        );

        // Extract byte positions of each required token to verify ordering.
        let pos_lo = ruleset.find("oifname \"lo\" accept").expect("lo rule missing");
        let pos_wgif = ruleset
            .find("oifname \"wg-gui0\" accept")
            .expect("wgif rule missing");
        let pos_endpoint = ruleset
            .find("ip daddr 203.0.113.7 udp dport 51820 accept")
            .expect("endpoint rule missing");
        let pos_lan_first = ruleset
            .find("ip daddr 192.168.0.0/16 accept")
            .expect("first LAN rule missing");
        let pos_lan_second = ruleset
            .find("ip daddr 10.0.0.0/8 accept")
            .expect("second LAN rule missing");
        let pos_established = ruleset
            .find("ct state established,related accept")
            .expect("established rule missing");

        assert!(pos_lo < pos_wgif, "lo must come before wgif");
        assert!(pos_wgif < pos_endpoint, "wgif must come before endpoint");
        assert!(pos_endpoint < pos_lan_first, "endpoint must come before LAN");
        assert!(pos_lan_first < pos_lan_second, "first LAN before second LAN");
        assert!(pos_lan_second < pos_established, "LAN must come before established");
    }

    #[test]
    fn allow_list_ordering_without_lan() {
        let ruleset = build_ruleset("wg-gui1", "198.51.100.1", 13231, &[], None);

        let pos_lo = ruleset.find("oifname \"lo\" accept").expect("lo rule missing");
        let pos_wgif = ruleset
            .find("oifname \"wg-gui1\" accept")
            .expect("wgif rule missing");
        let pos_endpoint = ruleset
            .find("ip daddr 198.51.100.1 udp dport 13231 accept")
            .expect("endpoint rule missing");
        let pos_established = ruleset
            .find("ct state established,related accept")
            .expect("established rule missing");

        assert!(pos_lo < pos_wgif);
        assert!(pos_wgif < pos_endpoint);
        assert!(pos_endpoint < pos_established);
    }

    #[test]
    fn allow_list_ordering_with_netns_udp() {
        let ruleset = build_ruleset(
            "wg-gui0",
            "203.0.113.7",
            51820,
            &["10.0.0.0/8"],
            Some(("203.0.113.7", 51820)),
        );

        let pos_established = ruleset
            .find("ct state established,related accept")
            .expect("established missing");
        // The netns punch-through must appear AFTER established (rule 6).
        // We use the second occurrence of the endpoint accept line (the netns one).
        let first_ep = ruleset
            .find("ip daddr 203.0.113.7 udp dport 51820 accept")
            .expect("first endpoint missing");
        let second_ep = ruleset
            .rfind("ip daddr 203.0.113.7 udp dport 51820 accept")
            .expect("second endpoint missing");

        // There must be two occurrences (rule 3 + rule 6).
        assert_ne!(first_ep, second_ep, "expected two endpoint-udp rules");
        assert!(
            pos_established < second_ep,
            "established must precede netns punch-through"
        );
    }

    // ── build_ruleset: structural invariants ─────────────────────────────────

    #[test]
    fn table_and_chain_names_present() {
        let r = build_ruleset("wg0", "1.2.3.4", 51820, &[], None);
        assert!(r.contains("table inet wg_gui_killswitch"), "table name missing");
        assert!(r.contains("chain output"), "output chain missing");
    }

    #[test]
    fn flush_then_recreate_pattern_present() {
        // The script must add then delete the table before creating it, making re-arm idempotent.
        let r = build_ruleset("wg0", "1.2.3.4", 51820, &[], None);
        let pos_add = r.find("add table inet wg_gui_killswitch").expect("add missing");
        let pos_del = r
            .find("delete table inet wg_gui_killswitch")
            .expect("delete missing");
        let pos_create = r
            .rfind("table inet wg_gui_killswitch {")
            .expect("create block missing");
        assert!(pos_add < pos_del, "add must precede delete");
        assert!(pos_del < pos_create, "delete must precede create block");
    }

    #[test]
    fn lan_cidrs_all_emitted() {
        let cidrs = &["192.168.0.0/16", "172.16.0.0/12", "10.0.0.0/8"];
        let r = build_ruleset("wg0", "1.2.3.4", 51820, cidrs, None);
        for cidr in cidrs {
            assert!(
                r.contains(&format!("ip daddr {} accept", cidr)),
                "CIDR {cidr} missing from ruleset"
            );
        }
    }

    #[test]
    fn no_netns_rule_when_none() {
        // When netns_endpoint_udp is None, rule 6 should be a comment, not an accept rule.
        let r = build_ruleset("wg0", "1.2.3.4", 51820, &[], None);
        // Count occurrences of "accept" lines that are not comments.
        let accept_lines: Vec<&str> = r
            .lines()
            .filter(|l| l.trim_start().starts_with("ip daddr") && l.contains("accept"))
            .collect();
        // Without netns: only the endpoint rule (rule 3). No second netns rule.
        assert_eq!(accept_lines.len(), 1, "expected exactly 1 ip daddr accept line, got: {accept_lines:?}");
    }

    // ── nft syntax check (requires nft, marks #[ignore] if absent) ───────────

    /// Check whether `nft` is available. Used to conditionally mark tests.
    fn nft_available() -> bool {
        Command::new("nft").arg("--version").output().is_ok()
    }

    /// Run `nft -c -f <file>` (syntax check ONLY — never applies anything) and return true iff
    /// exit status is 0.
    fn nft_check(ruleset: &str) -> std::io::Result<bool> {
        let tmp = write_temp_ruleset(ruleset);
        let status = Command::new("nft")
            .arg("-c")
            .arg("-f")
            .arg(tmp.path())
            .status()?;
        Ok(status.success())
    }

    /// Full ruleset with LAN CIDRs + netns punch-through passes nft syntax check.
    ///
    /// Tagged `#[ignore]` — the CI runner may not have nft (or may lack the kernel module for
    /// the check).  Run manually on a box with nft installed to confirm.
    #[test]
    #[ignore]
    fn nft_syntax_check_full_ruleset() {
        if !nft_available() {
            eprintln!("nft not found — skipping syntax check");
            return;
        }
        let ruleset = build_ruleset(
            "wg-gui0",
            "203.0.113.7",
            51820,
            &["192.168.0.0/16", "10.0.0.0/8"],
            Some(("203.0.113.7", 51820)),
        );
        assert!(
            nft_check(&ruleset).expect("nft invocation failed"),
            "nft -c rejected the ruleset:\n{ruleset}"
        );
    }

    /// Minimal ruleset (no LAN, no netns) passes nft syntax check.
    #[test]
    #[ignore]
    fn nft_syntax_check_minimal_ruleset() {
        if !nft_available() {
            eprintln!("nft not found — skipping syntax check");
            return;
        }
        let ruleset = build_ruleset("wg0", "1.2.3.4", 51820, &[], None);
        assert!(
            nft_check(&ruleset).expect("nft invocation failed"),
            "nft -c rejected the minimal ruleset:\n{ruleset}"
        );
    }

    /// An intentionally broken ruleset must NOT pass the syntax check, confirming the test
    /// actually calls nft and is not trivially always-true.
    #[test]
    #[ignore]
    fn nft_syntax_check_rejects_bad_ruleset() {
        if !nft_available() {
            eprintln!("nft not found — skipping syntax check");
            return;
        }
        let bad = "table inet wg_gui_killswitch { this is not valid nft syntax !!! }";
        assert!(
            !nft_check(bad).expect("nft invocation failed"),
            "nft -c should have rejected the bad ruleset"
        );
    }

    // ── KillSwitch::arm_cmd / disarm_cmd (pure, no execution) ─────────────────

    #[test]
    fn arm_cmd_produces_valid_json_with_all_fields() {
        let json = KillSwitch::arm_cmd(
            "wg-gui0",
            "203.0.113.7",
            51820,
            vec!["192.168.0.0/16".into(), "10.0.0.0/8".into()],
            30,
            Some(("203.0.113.7".into(), 51820)),
        )
        .expect("encode failed");

        assert!(json.contains(r#""cmd":"KillSwitchArm""#), "tag missing: {json}");
        assert!(json.contains(r#""iface":"wg-gui0""#));
        assert!(json.contains(r#""endpoint_ip":"203.0.113.7""#));
        assert!(json.contains(r#""endpoint_port":51820"#));
        assert!(json.contains(r#""lease_secs":30"#));
    }

    #[test]
    fn arm_cmd_none_netns_roundtrips() {
        let json = KillSwitch::arm_cmd(
            "wg0",
            "198.51.100.1",
            13231,
            vec![],
            60,
            None,
        )
        .expect("encode");
        let back: PrivCmd = serde_json::from_str(&json).expect("decode");
        assert_eq!(
            back,
            PrivCmd::KillSwitchArm {
                iface: "wg0".into(),
                endpoint_ip: "198.51.100.1".into(),
                endpoint_port: 13231,
                lan_cidrs: vec![],
                lease_secs: 60,
                netns_endpoint_udp: None,
            }
        );
    }

    #[test]
    fn disarm_cmd_is_unit_variant_json() {
        let json = KillSwitch::disarm_cmd().expect("encode");
        assert_eq!(json, r#"{"cmd":"KillSwitchDisarm"}"#);
    }

    // ── NFT_TABLE constant ─────────────────────────────────────────────────────

    #[test]
    fn nft_table_constant_matches_ruleset() {
        // The constant must match what build_ruleset embeds, so the helper and the GUI agree.
        let r = build_ruleset("wg0", "1.2.3.4", 51820, &[], None);
        assert!(
            r.contains("wg_gui_killswitch"),
            "ruleset does not contain the expected table name"
        );
        assert_eq!(NFT_TABLE, "inet wg_gui_killswitch");
    }

    // ── Iface name injection safety ────────────────────────────────────────────

    #[test]
    fn iface_name_is_quoted_in_oifname_rules() {
        let r = build_ruleset("wg-gui-home", "1.2.3.4", 51820, &[], None);
        // nftables requires interface names in string matching to be quoted.
        assert!(
            r.contains(r#"oifname "wg-gui-home" accept"#),
            "iface name must be double-quoted in oifname rule: {r}"
        );
        assert!(
            r.contains(r#"oifname "lo" accept"#),
            "lo must be double-quoted: {r}"
        );
    }

    // ── Lease + dead-man timer documentation test ─────────────────────────────

    /// This test does NOT execute systemd-run.  It is purely a golden-string check that the
    /// expected systemd-run command shape (which the HELPER will construct) is documented
    /// correctly in this module and matches the design spec.
    ///
    /// The helper MUST run exactly this command after `nft -f <ruleset>`:
    ///
    /// ```text
    /// systemd-run --on-active=<lease_secs>s \
    ///             --unit=wg-gui-killswitch-reaper \
    ///             --description="WireGuard GUI kill-switch lease reaper" \
    ///             nft delete table inet wg_gui_killswitch
    /// ```
    #[test]
    fn dead_man_timer_command_shape_golden() {
        // Build the argv the helper is supposed to construct for lease_secs=30.
        let lease_secs: u64 = 30;
        let expected_argv = vec![
            "systemd-run".to_string(),
            format!("--on-active={}s", lease_secs),
            "--unit=wg-gui-killswitch-reaper".to_string(),
            "--description=WireGuard GUI kill-switch lease reaper".to_string(),
            "nft".to_string(),
            "delete".to_string(),
            "table".to_string(),
            "inet".to_string(),
            "wg_gui_killswitch".to_string(),
        ];

        // Verify the command structure without executing it.
        assert_eq!(expected_argv[0], "systemd-run");
        assert_eq!(expected_argv[1], "--on-active=30s");
        assert_eq!(expected_argv[2], "--unit=wg-gui-killswitch-reaper");
        assert_eq!(expected_argv[4], "nft");
        // The final argument to nft must name the table constant we export.
        assert_eq!(
            expected_argv.last().unwrap().as_str(),
            "wg_gui_killswitch"
        );
        // Full argv length sanity.
        assert_eq!(expected_argv.len(), 9);
    }
}
