//! Server-side NAT masquerade — pure builders and GUI-side dispatchers.
//!
//! # Design
//!
//! The server needs source NAT (masquerade) so tunnel clients can reach the internet
//! through this host.  The implementation uses a uniquely-named nftables table
//! (`inet wg_gui_srv_nat`) — the same unique-name pattern as the kill-switch — so it
//! never collides with any user-managed firewall table.
//!
//! ## What the NAT table does
//!
//! ```text
//! table inet wg_gui_srv_nat {
//!     chain postrouting {
//!         type nat hook postrouting priority 100;
//!         ip saddr <subnet> oifname "<egress_iface>" masquerade;
//!     }
//! }
//! ```
//!
//! All IPv4 traffic sourced from `subnet` (e.g. `10.7.0.0/24`) that leaves
//! `egress_iface` (e.g. `eth0`) is masqueraded as the host's own IP.  This lets
//! WireGuard clients reach the internet without static SNAT entries.
//!
//! ## IPv4 forwarding
//!
//! `NatEnable` also enables kernel IP forwarding:
//!   - `sysctl -w net.ipv4.ip_forward=1`
//!   - `sysctl -w net.ipv6.conf.all.forwarding=1` (best-effort)
//!
//! Forwarding is intentionally NOT disabled on `NatDisable` — other services
//! on the same host may depend on it being set.
//!
//! ## Privilege boundary
//!
//! This module is **pure GUI-side**.  It builds [`PrivCmd`] values and pure
//! ruleset / argv text; it never runs any privileged command.  The actual
//! `sysctl`, `nft -f`, and `nft delete table` invocations happen exclusively
//! inside the root `wireguard-gui-helper` binary.

use crate::error::AppResult;
use crate::net::privilege::{encode, run_privileged, PrivCmd};

// ─────────────────────────────────────────────────────────────────────────────
// Constants
// ─────────────────────────────────────────────────────────────────────────────

/// The nftables table used exclusively for server masquerade NAT.
///
/// Uniquely named so it never collides with user-managed tables or the
/// kill-switch table.
pub const NFT_NAT_TABLE: &str = "inet wg_gui_srv_nat";

// ─────────────────────────────────────────────────────────────────────────────
// Pure builders (golden-testable, no I/O, no root)
// ─────────────────────────────────────────────────────────────────────────────

/// Build the complete `nft -f` script text that installs the server masquerade
/// ruleset.
///
/// The returned string is a self-contained nftables script that:
/// - Creates `table inet wg_gui_srv_nat` with a `nat hook postrouting` chain
/// - Adds `ip saddr <subnet> oifname "<egress_iface>" masquerade`
///
/// # Parameters
///
/// - `subnet`        — the tunnel subnet to masquerade (e.g. `"10.7.0.0/24"`)
/// - `egress_iface`  — the host's internet-facing interface (e.g. `"eth0"`)
///
/// # Guarantee
///
/// This function is **pure** and never executes any command.  Pass the output to
/// a temp file and invoke `nft -c -f <file>` (syntax check only) or let the
/// helper run `nft -f <file>` to apply.
pub fn build_nat_ruleset(subnet: &str, egress_iface: &str) -> String {
    format!(
        "# wg_gui_srv_nat — generated by wireguard-gui-rust\n\
         # DO NOT EDIT MANUALLY — managed by wireguard-gui-helper\n\
         \n\
         table inet wg_gui_srv_nat {{\n\
             chain postrouting {{\n\
                 type nat hook postrouting priority 100;\n\
                 ip saddr {subnet} oifname \"{egress_iface}\" masquerade;\n\
             }}\n\
         }}\n"
    )
}

/// Build the `sysctl -w net.ipv4.ip_forward=1` argv.
///
/// Pure.  The helper executes this; the GUI only builds it (e.g. for golden
/// tests or dry-run previews).
pub fn sysctl_ipv4_forward_argv() -> Vec<String> {
    vec![
        "sysctl".into(),
        "-w".into(),
        "net.ipv4.ip_forward=1".into(),
    ]
}

/// Build the `sysctl -w net.ipv6.conf.all.forwarding=1` argv.
///
/// Pure.  Applied best-effort in the helper (non-fatal if IPv6 is absent).
pub fn sysctl_ipv6_forward_argv() -> Vec<String> {
    vec![
        "sysctl".into(),
        "-w".into(),
        "net.ipv6.conf.all.forwarding=1".into(),
    ]
}

/// Build the `nft delete table inet wg_gui_srv_nat` argv.
///
/// Family and table name are SEPARATE arguments — mirrors the kill-switch pattern
/// and matches how `nft` parses its command line.  Pass `argv[0]` as the program
/// and `argv[1..]` as the args.
pub fn nft_delete_nat_table_argv() -> Vec<String> {
    vec![
        "nft".into(),
        "delete".into(),
        "table".into(),
        "inet".into(),
        "wg_gui_srv_nat".into(),
    ]
}

// ─────────────────────────────────────────────────────────────────────────────
// Client-side helpers — build and dispatch PrivCmd values
// ─────────────────────────────────────────────────────────────────────────────

/// GUI-side server NAT controller.
///
/// All methods are **pure builders or async dispatchers**.  The actual sysctl /
/// nft execution happens only inside the root helper binary (via `pkexec`); this
/// struct never runs privileged code.
pub struct ServerNat;

impl ServerNat {
    /// Enable NAT masquerade for `subnet` out `egress_iface`.
    ///
    /// Dispatches [`PrivCmd::NatEnable`] through the privileged helper.  The helper
    /// will:
    ///   1. `sysctl -w net.ipv4.ip_forward=1`
    ///   2. `sysctl -w net.ipv6.conf.all.forwarding=1` (best-effort)
    ///   3. Apply the masquerade nft ruleset via `nft -f <tempfile>`.
    pub async fn enable(&self, subnet: &str, egress_iface: &str) -> AppResult<()> {
        let cmd = PrivCmd::NatEnable {
            subnet: subnet.to_owned(),
            egress_iface: egress_iface.to_owned(),
        };
        run_privileged(&cmd).await
    }

    /// Disable NAT masquerade: remove the `wg_gui_srv_nat` table.
    ///
    /// Dispatches [`PrivCmd::NatDisable`] through the privileged helper.  The helper
    /// runs `nft delete table inet wg_gui_srv_nat`.  Idempotent — if the table is
    /// already absent, the helper treats it as success.
    pub async fn disable(&self) -> AppResult<()> {
        run_privileged(&PrivCmd::NatDisable).await
    }

    /// Build the [`PrivCmd::NatEnable`] payload **without dispatching it**.
    ///
    /// Use for golden-string tests, dry-run previews, or anywhere the JSON wire
    /// shape must be inspected without executing anything.
    pub fn enable_cmd(subnet: &str, egress_iface: &str) -> AppResult<String> {
        let cmd = PrivCmd::NatEnable {
            subnet: subnet.to_owned(),
            egress_iface: egress_iface.to_owned(),
        };
        encode(&cmd)
    }

    /// Build the [`PrivCmd::NatDisable`] payload without dispatching it.
    pub fn disable_cmd() -> AppResult<String> {
        encode(&PrivCmd::NatDisable)
    }

    /// Build the [`PrivCmd::ServerWriteConf`] payload without dispatching it.
    pub fn server_write_conf_cmd(conf_text: &str) -> AppResult<String> {
        let cmd = PrivCmd::ServerWriteConf {
            conf_text: conf_text.to_owned(),
        };
        encode(&cmd)
    }

    /// Build the [`PrivCmd::ServerUp`] payload without dispatching it.
    pub fn server_up_cmd() -> AppResult<String> {
        encode(&PrivCmd::ServerUp)
    }

    /// Build the [`PrivCmd::ServerDown`] payload without dispatching it.
    pub fn server_down_cmd() -> AppResult<String> {
        encode(&PrivCmd::ServerDown)
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use std::process::Command;

    use super::*;

    // ── build_nat_ruleset: structural invariants ──────────────────────────────

    #[test]
    fn nat_ruleset_contains_table_name() {
        let rs = build_nat_ruleset("10.7.0.0/24", "eth0");
        assert!(
            rs.contains("wg_gui_srv_nat"),
            "table name missing: {rs}"
        );
        assert!(rs.contains("inet"), "family 'inet' missing: {rs}");
    }

    #[test]
    fn nat_ruleset_contains_postrouting_chain() {
        let rs = build_nat_ruleset("10.7.0.0/24", "eth0");
        assert!(rs.contains("postrouting"), "postrouting hook missing: {rs}");
        assert!(rs.contains("priority 100"), "priority 100 missing: {rs}");
    }

    #[test]
    fn nat_ruleset_contains_masquerade() {
        let rs = build_nat_ruleset("10.7.0.0/24", "eth0");
        assert!(rs.contains("masquerade"), "masquerade target missing: {rs}");
    }

    #[test]
    fn nat_ruleset_subnet_embedded() {
        let rs = build_nat_ruleset("10.7.0.0/24", "eth0");
        assert!(
            rs.contains("ip saddr 10.7.0.0/24"),
            "subnet not found in ruleset: {rs}"
        );
    }

    #[test]
    fn nat_ruleset_egress_iface_quoted() {
        // nftables requires interface names to be quoted in string-match rules.
        let rs = build_nat_ruleset("10.7.0.0/24", "eth0");
        assert!(
            rs.contains(r#"oifname "eth0""#),
            "egress iface must be double-quoted in oifname: {rs}"
        );
    }

    #[test]
    fn nat_ruleset_different_params_differ() {
        let a = build_nat_ruleset("10.7.0.0/24", "eth0");
        let b = build_nat_ruleset("192.168.100.0/24", "ens3");
        assert_ne!(a, b, "different params must yield different rulesets");
    }

    #[test]
    fn nat_ruleset_has_generated_comment() {
        let rs = build_nat_ruleset("10.7.0.0/24", "eth0");
        assert!(
            rs.contains("wireguard-gui-rust"),
            "generated-by comment missing: {rs}"
        );
        assert!(
            rs.contains("DO NOT EDIT MANUALLY"),
            "do-not-edit comment missing: {rs}"
        );
    }

    // ── sysctl argv builders (golden, no execution) ───────────────────────────

    #[test]
    fn sysctl_ipv4_forward_argv_golden() {
        assert_eq!(
            sysctl_ipv4_forward_argv(),
            vec!["sysctl", "-w", "net.ipv4.ip_forward=1"]
        );
    }

    #[test]
    fn sysctl_ipv6_forward_argv_golden() {
        assert_eq!(
            sysctl_ipv6_forward_argv(),
            vec!["sysctl", "-w", "net.ipv6.conf.all.forwarding=1"]
        );
    }

    // ── nft_delete_nat_table_argv (golden) ────────────────────────────────────

    #[test]
    fn nft_delete_nat_table_argv_shape() {
        let argv = nft_delete_nat_table_argv();
        assert_eq!(argv.len(), 5, "expected 5 elements: {argv:?}");
        assert_eq!(argv[0], "nft");
        assert_eq!(argv[1], "delete");
        assert_eq!(argv[2], "table");
        // Family and name MUST be separate arguments.
        assert_eq!(argv[3], "inet", "family must be 'inet'");
        assert_eq!(argv[4], "wg_gui_srv_nat", "name must be 'wg_gui_srv_nat'");
    }

    #[test]
    fn nft_delete_nat_table_family_and_name_are_separate() {
        // Guard: the argv must NOT contain "inet wg_gui_srv_nat" as a single element.
        let argv = nft_delete_nat_table_argv();
        assert!(
            !argv.iter().any(|a| a == "inet wg_gui_srv_nat"),
            "family+name must not be a single argument: {argv:?}"
        );
    }

    // ── NFT_NAT_TABLE constant ────────────────────────────────────────────────

    #[test]
    fn nft_nat_table_constant_matches_ruleset() {
        let rs = build_nat_ruleset("10.7.0.0/24", "eth0");
        assert!(
            rs.contains("wg_gui_srv_nat"),
            "ruleset does not contain the table name from NFT_NAT_TABLE"
        );
        assert_eq!(NFT_NAT_TABLE, "inet wg_gui_srv_nat");
    }

    // ── ServerNat cmd builders (pure, no execution) ───────────────────────────

    #[test]
    fn enable_cmd_produces_tagged_json() {
        let json = ServerNat::enable_cmd("10.7.0.0/24", "eth0").expect("encode");
        assert!(json.contains(r#""cmd":"NatEnable""#), "tag missing: {json}");
        assert!(json.contains(r#""subnet":"10.7.0.0/24""#), "subnet missing: {json}");
        assert!(json.contains(r#""egress_iface":"eth0""#), "egress missing: {json}");
    }

    #[test]
    fn disable_cmd_is_unit_variant_json() {
        let json = ServerNat::disable_cmd().expect("encode");
        assert_eq!(json, r#"{"cmd":"NatDisable"}"#);
    }

    #[test]
    fn server_write_conf_cmd_tagged_json() {
        let conf = "[Interface]\nPrivateKey = x\nListenPort = 51820\n";
        let json = ServerNat::server_write_conf_cmd(conf).expect("encode");
        assert!(
            json.contains(r#""cmd":"ServerWriteConf""#),
            "tag missing: {json}"
        );
        assert!(json.contains(r#""conf_text""#), "conf_text field missing: {json}");
    }

    #[test]
    fn server_up_cmd_unit_variant_json() {
        let json = ServerNat::server_up_cmd().expect("encode");
        assert_eq!(json, r#"{"cmd":"ServerUp"}"#);
    }

    #[test]
    fn server_down_cmd_unit_variant_json() {
        let json = ServerNat::server_down_cmd().expect("encode");
        assert_eq!(json, r#"{"cmd":"ServerDown"}"#);
    }

    #[test]
    fn server_up_and_down_cmds_are_distinct() {
        let up = ServerNat::server_up_cmd().expect("up");
        let down = ServerNat::server_down_cmd().expect("down");
        assert_ne!(up, down, "ServerUp and ServerDown must have different JSON");
    }

    #[test]
    fn enable_cmd_round_trips_through_priv_cmd() {
        let json = ServerNat::enable_cmd("10.7.0.0/24", "eth0").expect("encode");
        let back: crate::net::privilege::PrivCmd =
            serde_json::from_str(&json).expect("decode");
        assert_eq!(
            back,
            crate::net::privilege::PrivCmd::NatEnable {
                subnet: "10.7.0.0/24".into(),
                egress_iface: "eth0".into(),
            }
        );
    }

    #[test]
    fn disable_cmd_round_trips_through_priv_cmd() {
        let json = ServerNat::disable_cmd().expect("encode");
        let back: crate::net::privilege::PrivCmd =
            serde_json::from_str(&json).expect("decode");
        assert_eq!(back, crate::net::privilege::PrivCmd::NatDisable);
    }

    // ── nft syntax check (requires nft binary — mark #[ignore]) ──────────────

    fn nft_available() -> bool {
        Command::new("nft").arg("--version").output().is_ok()
    }

    fn nft_check_syntax(ruleset: &str) -> std::io::Result<bool> {
        use std::io::Write as _;
        let mut f = tempfile::NamedTempFile::new()?;
        f.write_all(ruleset.as_bytes())?;
        let status = Command::new("nft")
            .arg("-c")
            .arg("-f")
            .arg(f.path())
            .status()?;
        Ok(status.success())
    }

    /// Full masquerade ruleset passes `nft -c -f` (syntax check ONLY — never
    /// applies any NAT rule or networking change).
    ///
    /// Tagged `#[ignore]` — CI runner may not have nft installed or may lack
    /// the kernel module for the check.  Run manually to confirm.
    #[test]
    #[ignore]
    fn nft_nat_ruleset_syntax_check_full() {
        if !nft_available() {
            eprintln!("nft not found — skipping NAT syntax check");
            return;
        }
        let ruleset = build_nat_ruleset("10.7.0.0/24", "eth0");
        assert!(
            nft_check_syntax(&ruleset).expect("nft invocation failed"),
            "nft -c rejected the NAT masquerade ruleset:\n{ruleset}"
        );
    }

    /// Different egress / subnet combinations all pass the syntax check.
    #[test]
    #[ignore]
    fn nft_nat_ruleset_syntax_check_variations() {
        if !nft_available() {
            return;
        }
        let cases = [
            ("10.7.0.0/24", "eth0"),
            ("192.168.100.0/24", "ens3"),
            ("172.16.0.0/12", "wlan0"),
        ];
        for (subnet, iface) in cases {
            let rs = build_nat_ruleset(subnet, iface);
            assert!(
                nft_check_syntax(&rs).expect("nft invocation failed"),
                "nft -c rejected ruleset for subnet={subnet} iface={iface}:\n{rs}"
            );
        }
    }

    /// An intentionally broken ruleset MUST be rejected, confirming the test
    /// actually invokes nft and is not trivially always-true.
    #[test]
    #[ignore]
    fn nft_nat_syntax_check_rejects_bad_ruleset() {
        if !nft_available() {
            return;
        }
        let bad = "table inet wg_gui_srv_nat { this is not valid !!! }";
        assert!(
            !nft_check_syntax(bad).expect("nft invocation failed"),
            "nft -c should have rejected the bad ruleset"
        );
    }
}
